
exports.REACT_APP_CREATE_USER_URL = process.env.REACT_APP_CREATE_USER_URL;
exports.REACT_APP_USER_LOGIN_URL = process.env.REACT_APP_USER_LOGIN_URL;
exports.REACT_APP_FAVS_URL = process.env.REACT_APP_FAVS_URL;
exports.REACT_APP_USERFAVS_URL = process.env.REACT_APP_USERFAVS_URL;
exports.REACT_APP_FAV_SEARCH_DETAIL_URL = process.env.REACT_APP_FAV_SEARCH_DETAIL_URL;
exports.REACT_APP_FAV_YELP_URL = process.env.REACT_APP_FAV_YELP_URL;
exports.REACT_APP_TEST_USERNAME = process.env.REACT_APP_TEST_USERNAME;
exports.REACT_APP_TEST_PASSWORD = process.env.REACT_APP_TEST_PASSWORD;
exports.REACT_APP_TEST_PASSWORD = process.env.REACT_APP_TEST_PASSWORD;